### ISSUE TITLE
SplitMeshPart gets stuck trying to split an already split mesh

### ISSUE THREAD

**Issue by Bloodstability** [MaxxWyndham/Flummery#96]
Importing a vehicle and saving as >CR vehicle works fine.

If I do the following

Import > Save As > CR > Vehicle
Delete the contents of the folder the car was output to
in the same session go Save As > CR > Vehicle into the same folder, Flummery will crash.

**Comment by MaxxWyndham** [comment]
@Bloodstability Couldn't recreate in my current dev build.  Let me know if you can in 0.3.7.4
